### ISSUE TITLE
Logo image not updating

### ISSUE THREAD

**Issue by torieketcham** [marinebon/old_marinebon.github.io#8]
I uploaded a new OBIS logo and updated the path on the data/navigation.yml file (from obis_logo.png to obis_logo_updated.png) and committed on Thursday, but the changes aren't appearing. What do you think could be happening? I tried to look on Travis to see but it doesn't seem to be supported anymore.

**Comment by 7yl4r** [comment]
This is pretty weird. Looking at the commit history I see that Travis did not build the site.

I logged into travis-ci.com and the marinebon.github.io repo was not enabled. Weird but whatever I'll just add it back, right? Well no... Travis can't find it at all!

![image](https://user-images.githubusercontent.com/1051390/122811661-c3687280-d29e-11eb-9b48-3e39b1c4566e.png)

Some things I have checked:

1. I looked at the settings for the marinebon org and it is set to "All repositories" as it should be. 
2. Rather then searching in the travis interface I manually looked through the alphabetical list and marinebon.github.io is not there either.

Some searching revealed some similar reported issues:

1. https://github.com/travis-ci/travis-ci/issues/8689
2. https://travis-ci.community/t/github-repo-doesnt-appear-in-travis/4263

--------------------------------------

Turns out you can still get to the travis stuff by going to the link directly: https://travis-ci.com/github/marinebon/marinebon.github.io

Weirdness:
1. I tried to manually trigger the build and got a ` Oh no! Oops, something went wrong, please try again. ` error message.
2. I went to the build history and found `No builds for this repository` - well that is not right either.

----------------------------------------

I can also get to the deprecated interface at https://travis-ci.org/github/marinebon/marinebon.github.io

---------------------------------------

Ohhhh okay. We just need to migrate from `.org` to `.com`. Instructions [here](https://docs.travis-ci.com/user/migrate/open-source-repository-migration). 

1. went to + repo on travis-ci.com, migrate tab
2. signed up for the beta
3. checked marinebon.github.io
4. went to the repo page on travis-ci.com
5. manually triggered build (at 15:10)
6. waited until 17:03 (~2hr)
7. did a commit to edit the README.md via github GUI
8. waited ~45m and still no build; the hooks must not be working either.
9. Not sure what else to try to get travis working

----------------------------------

If we are not able to get travis working then I will build the `src` branch and push the `master` using my PC. That is not ideal but maybe it is fine since this repo is approaching end-of-life anyway.

**Comment by torieketcham** [comment]
Yikes. Do you think we should go ahead with that solution? I don't want to add to your workload but I do feel like we should get this particular commit published (and we'll likely have more changes to make to the current site before we switch to the new one, so we'll need an interim solution).

**Comment by 7yl4r** [comment]
Yes, I will do it now.

-------------------------------

Following the dev section of the README I ran into some unexepected complications:

1. I had to modify my `$PATH` to add the jekyll bundler binaries. I did this by editing my `.bashrc`.
2. I got the following error when trying to bundle the site:
    ```
    Error: could not read file /home/tylar/git-repos/marinebon.github.io/vendor/bundle/ruby/2.7.0/gems/jekyll-3.9.0/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb: Invalid date '<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>': Document 'vendor/bundle/ruby/2.7.0/gems/jekyll-3.9.0/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the YAML front matter.
    ```
    
    I worked around this by removing that file.
3. Trying to build the site I get the following error:
    ```
    Liquid Exception: Liquid syntax error (line 8): Unknown tag 'when' in vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/locales/en.yml
    ```

Perhaps I have a mismatched version problem. I will reassess and try again tomorrow.

**Comment by torieketcham** [comment]
Joana's most recent email reminded me about this - were you able to troubleshoot the issues with building the site? I'd like to be able to publish that updated logo from last week before she asks me about it again...

**Comment by 7yl4r** [comment]
Following instructions from related [SO A](https://stackoverflow.com/a/47571535/1483986). Ran into another issue similar to [this SO Q](https://stackoverflow.com/questions/56358405/your-bundle-is-locked-to-ffi-1-11-0-but-that-version-could-not-be-found-in-an). 

```bash
[tylar@tylar-pc marinebon.github.io]$ rm -r .bundle
[tylar@tylar-pc marinebon.github.io]$ rm -rf vendor
[tylar@tylar-pc marinebon.github.io]$ bundle install
Fetching gem metadata from https://rubygems.org/
Fetching gem metadata from https://rubygems.org/.........
Your bundle is locked to dnsruby (1.61.6) from rubygems repository https://rubygems.org/ or
installed locally, but that version can no longer be found in that source. That means the author
of dnsruby (1.61.6) has removed it. You'll need to update your bundle to a version other than
dnsruby (1.61.6) that hasn't been removed in order to install.

[tylar@tylar-pc marinebon.github.io]$ bundle update
[...]
Following files may not be writable, so sudo is needed:
  /usr/bin
  /usr/lib/ruby/gems/2.7.0
  /usr/lib/ruby/gems/2.7.0/build_info
  /usr/lib/ruby/gems/2.7.0/cache
  /usr/lib/ruby/gems/2.7.0/doc
  /usr/lib/ruby/gems/2.7.0/extensions
  /usr/lib/ruby/gems/2.7.0/gems
  /usr/lib/ruby/gems/2.7.0/specifications
[...]

[tylar@tylar-pc marinebon.github.io]$ bundle exec jekyll serve
[...]
Configuration file: /home/tylar/git-repos/marinebon.github.io/_config.yml
       Deprecation: The 'gems' configuration option has been renamed to 'plugins'. Please update your config file accordingly.
            Source: .
       Destination: _site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       Jekyll Feed: Generating feed for posts
   GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
in Sass 4.0. Use call(get-function("mixin-exists")) instead.

DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
in Sass 4.0. Use call(get-function("variable-exists")) instead.
[...]

                    done in 10.524 seconds.
/home/tylar/.gem/ruby/2.7.0/gems/pathutil-0.16.2/lib/pathutil.rb:502: warning: Using the last argument as keyword parameters is deprecated
 Auto-regeneration: enabled for '.'
    Server address: http://127.0.0.1:4000
  Server running... press ctrl-c to stop.
```

There we go. All looks good. 

I just pushed the build to github & added instructions for doing so to the README.

All looks good I think. The site is now up-to-date.

For now @torieketcham please @ or email me when you want this rebuilt. I will need to rebuild any time we want changes to show on marinebon.org.
